version: 2
updates:
  # npm のバージョン更新を有効にする
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      timezone: 'Asia/Tokyo'
    ignore:
      - dependency-name: "husky"
        # 5.x の新しいバージョンのみを無視する
        versions: ["5.x"]
